"""Runtime configuration.

Values come from environment variables (prefix ``JARVIS_``) or a ``.env`` file
in the backend directory. Nothing here is secret: the per-launch API token is
generated by the desktop shell and passed in through the environment.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OLLAMA_MODELS = Path.home() / "Developer" / "ollama" / "models"


def _default_data_dir() -> Path:
    return Path.home() / "Library" / "Application Support" / "JarvisAssistant"


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="JARVIS_", env_file=".env", extra="ignore")

    # Server
    host: str = "127.0.0.1"
    port: int = 8765
    api_token: str = ""  # empty only for local development / tests

    # Storage
    data_dir: Path = _default_data_dir()
    models_dir: Path = REPO_ROOT / "models"

    # Camera
    camera_index: int = 0
    process_fps: float = 6.0  # face-analysis rate; camera itself runs faster
    preview_width: int = 320

    # Face verification
    face_model_pack: str = "buffalo_l"
    face_threshold: float = 0.42  # cosine similarity needed to accept a frame
    face_reject_threshold: float = 0.25  # below this a face is treated as a stranger
    face_top_k: int = 5
    face_window: int = 6  # frames in the smoothing window
    reauth_interval_s: float = 30.0  # approval expires without a fresh match
    absence_lock_s: float = 8.0  # owner away this long -> session locked
    min_face_quality: float = 0.35

    # Voice verification (ECAPA cosine similarity, top-k mean vs enrolled template)
    mic_device: str | None = None  # default input device
    voice_threshold: float = 0.50
    voice_reject_threshold: float = 0.30
    voice_top_k: int = 5
    voice_valid_s: float = 20.0  # a voice match counts for this long

    # Liveness (see jarvis/auth/liveness)
    liveness_enabled: bool = True
    liveness_pass_threshold: float = 0.6  # median passive live score needed to pass a challenge
    liveness_spoof_threshold: float = 0.25  # sustained median below this = spoof
    liveness_challenge_steps: int = 2  # "blink twice" + random others
    liveness_step_timeout_s: float = 8.0
    liveness_recheck_min_s: float = 300.0  # random re-challenge window while unlocked
    liveness_recheck_max_s: float = 900.0
    liveness_blink_gap_s: float = 150.0  # no natural blink this long -> re-challenge
    liveness_lost_reset_s: float = 5.0  # owner out of view this long -> re-prove
    challenge_fps: float = 12.0  # analysis rate while a challenge runs (blinks are short)

    # Speech I/O
    speech_enabled: bool = True
    stt_model: str = "small"  # faster-whisper size in models/whisper/<size>: small | medium
    tts_speed: float = 1.0
    followup_s: float = 8.0  # after "<name>" alone, listen this long without the name

    # Local LLM (Ollama)
    llm_model: str = "qwen2.5:7b"  # default; the owner can switch in Settings
    ollama_host: str = "127.0.0.1:11434"
    ollama_models_dir: Path | None = DEFAULT_OLLAMA_MODELS  # None = Ollama's own default
    llm_autostart: bool = True  # start `ollama serve` if no server is running
    llm_timeout_s: float = 90.0

    # Memory
    memory_enabled: bool = True
    embed_model: str = "bge-m3"  # multilingual sentence embeddings via Ollama

    # Auth levels + fusion (see jarvis/auth/levels.py)
    fusion_enabled: bool = True
    level1_min_prob: float = 0.5  # fusion score thresholds per level
    level2_min_prob: float = 0.8
    level3_min_prob: float = 0.9
    level2_voice_window_s: float = 60.0  # owner's voice verified this recently -> level 2
    level3_liveness_max_age_s: float = 600.0  # deletions need a liveness check this recent
    confirm_ttl_s: float = 30.0  # time to confirm a deletion

    # Keychain
    keychain_service: str = "jarvis-assistant"

    @property
    def db_path(self) -> Path:
        return self.data_dir / "jarvis.sqlite3"

    @property
    def fusion_model_path(self) -> Path:
        return self.data_dir / "fusion_model.json"

    @property
    def templates_dir(self) -> Path:
        return self.data_dir / "templates"


@lru_cache
def get_settings() -> Settings:
    return Settings()
