"""Runtime configuration.

Values come from environment variables (prefix ``JARVIS_``) or a ``.env`` file
in the backend directory. Nothing here is secret: the per-launch API token is
generated by the desktop shell and passed in through the environment.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict

REPO_ROOT = Path(__file__).resolve().parents[2]


def _default_data_dir() -> Path:
    return Path.home() / "Library" / "Application Support" / "JarvisAssistant"


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="JARVIS_", env_file=".env", extra="ignore")

    # Server
    host: str = "127.0.0.1"
    port: int = 8765
    api_token: str = ""  # empty only for local development / tests

    # Storage
    data_dir: Path = _default_data_dir()
    models_dir: Path = REPO_ROOT / "models"

    # Camera
    camera_index: int = 0
    process_fps: float = 6.0  # face-analysis rate; camera itself runs faster
    preview_width: int = 320

    # Face verification
    face_model_pack: str = "buffalo_l"
    face_threshold: float = 0.42  # cosine similarity needed to accept a frame
    face_reject_threshold: float = 0.25  # below this a face is treated as a stranger
    face_top_k: int = 5
    face_window: int = 6  # frames in the smoothing window
    reauth_interval_s: float = 30.0  # approval expires without a fresh match
    absence_lock_s: float = 8.0  # owner away this long -> session locked
    min_face_quality: float = 0.35

    # Keychain
    keychain_service: str = "jarvis-assistant"

    @property
    def db_path(self) -> Path:
        return self.data_dir / "jarvis.sqlite3"

    @property
    def templates_dir(self) -> Path:
        return self.data_dir / "templates"


@lru_cache
def get_settings() -> Settings:
    return Settings()
